title: maintenance Information
# description: Cayman Blog Theme is a clean, responsive blogging theme for Jekyll and Gitlab/GitHub Pages.
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://maintenance.sherpherd.net" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"
github:
  is_project_page: false

theme: # leave it empty

# social
author: Hawkins Sherpherd
image: /thumbnail-jumbo.png
twitter:
  username: HawkinsSherphed

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

